// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-jobs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function profileIdFor(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("No hireOS profile found for this account");
  return { supabase, profileId: data.id };
}

// src/lib/mcp/tools/list-jobs.ts
var list_jobs_default = defineTool({
  name: "list_jobs",
  title: "List imported jobs",
  description: "List job opportunities imported into hireOS for the signed-in user, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max jobs to return (default 20)."),
    status: z.string().optional().describe("Optional status filter, e.g. new, saved, applied."),
    search: z.string().optional().describe("Optional text to match against job title or company.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, status, search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    let query = supabase.from("imported_jobs").select("id,title,company,location,salary,source,url,status,imported_at").eq("profile_id", profileId).order("imported_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (search) query = query.or(`title.ilike.%${search}%,company.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-job.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_job_default = defineTool2({
  name: "get_job",
  title: "Get job details",
  description: "Get full details for one imported hireOS job, including description and AI match analysis.",
  inputSchema: { job_id: z2.string().describe("The imported job id.") },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    const { data, error } = await supabase.from("imported_jobs").select("id,title,company,location,salary,url,source,status,snippet,description,analysis,imported_at").eq("profile_id", profileId).eq("id", job_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Job not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { job: data } };
  }
});

// src/lib/mcp/tools/list-applications.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_applications_default = defineTool3({
  name: "list_applications",
  title: "List applications",
  description: "List the signed-in user's job applications tracked in hireOS with status and next action.",
  inputSchema: {
    status: z3.string().optional().describe("Optional status filter, e.g. applied, interview, rejected."),
    limit: z3.number().int().min(1).max(50).optional().describe("Max applications to return (default 25).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    let query = supabase.from("applications").select("id,title,company,status,applied_date,next_action,last_email_date,notes").eq("profile_id", profileId).order("applied_date", { ascending: false }).limit(limit ?? 25);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-application.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_application_default = defineTool4({
  name: "create_application",
  title: "Track a new application",
  description: "Add a job application to the signed-in user's hireOS application tracker.",
  inputSchema: {
    title: z4.string().describe("Role title."),
    company: z4.string().describe("Company name."),
    status: z4.string().optional().describe("Status, e.g. applied, interview. Defaults to applied."),
    applied_date: z4.string().optional().describe("ISO date (YYYY-MM-DD) the application was submitted."),
    next_action: z4.string().optional().describe("Next step to take."),
    notes: z4.string().optional().describe("Freeform notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    const { data, error } = await supabase.from("applications").insert({
      profile_id: profileId,
      title: input.title,
      company: input.company,
      status: input.status ?? "applied",
      applied_date: input.applied_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      next_action: input.next_action ?? null,
      notes: input.notes ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { application: data } };
  }
});

// src/lib/mcp/tools/update-application.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var update_application_default = defineTool5({
  name: "update_application",
  title: "Update an application",
  description: "Update the status, next action, or notes of an existing hireOS application.",
  inputSchema: {
    application_id: z5.string().describe("The application id to update."),
    status: z5.string().optional().describe("New status, e.g. interview, offer, rejected."),
    next_action: z5.string().optional().describe("New next action."),
    notes: z5.string().optional().describe("New notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ application_id, status, next_action, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const updates = {};
    if (status !== void 0) updates.status = status;
    if (next_action !== void 0) updates.next_action = next_action;
    if (notes !== void 0) updates.notes = notes;
    if (Object.keys(updates).length === 0) {
      return { content: [{ type: "text", text: "Nothing to update" }], isError: true };
    }
    const { supabase, profileId } = await profileIdFor(ctx);
    const { data, error } = await supabase.from("applications").update(updates).eq("id", application_id).eq("profile_id", profileId).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Application not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { application: data } };
  }
});

// src/lib/mcp/tools/get-resume.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_resume_default = defineTool6({
  name: "get_resume",
  title: "Get base resume",
  description: "Get the signed-in user's base hireOS resume: summary, experience, projects, education, skills.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    const { data, error } = await supabase.from("resumes").select("id,label,summary,experience,projects,education,skills,achievements,updated_at").eq("profile_id", profileId).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No resume saved yet" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { resume: data } };
  }
});

// src/lib/mcp/tools/list-workspaces.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z6 } from "npm:zod@^3.25.76";
var list_workspaces_default = defineTool7({
  name: "list_workspaces",
  title: "List job workspaces",
  description: "List hireOS job workspaces (tailored resume workspaces) with ATS score and match bucket.",
  inputSchema: {
    limit: z6.number().int().min(1).max(50).optional().describe("Max workspaces to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { supabase, profileId } = await profileIdFor(ctx);
    const { data, error } = await supabase.from("job_workspaces").select("id,role_title,company,status,ats_score,baseline_score,score_delta,match_bucket,updated_at").eq("profile_id", profileId).order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { workspaces: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "nkhothtftipsrvznyurv";
var mcp_default = defineMcp({
  name: "hireos",
  title: "hireOS",
  version: "0.1.0",
  instructions: "Tools for hireOS, a job-search workspace. Read the signed-in user's imported jobs, applications, tailored resume workspaces, and base resume, and create or update tracked applications.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_jobs_default, get_job_default, list_applications_default, create_application_default, update_application_default, get_resume_default, list_workspaces_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
